// Pages Table
export const sqlPages = `
  CREATE TABLE IF NOT EXISTS pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT,
    featured_image TEXT,
    meta_title TEXT,
    meta_description TEXT,
    meta_keywords TEXT,
    seo_heading TEXT,
    canonical_url TEXT,
    is_published INTEGER DEFAULT 1, -- SQLite uses INTEGER for boolean (0 or 1)
    page_order INTEGER,
    created_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
  CREATE INDEX IF NOT EXISTS idx_pages_slug ON pages(slug);

`;

export const pagesData: any[] = [
  {
    title: "Dashboard",
    slug: "dashboard",
    content: "<h1>Welcome to the Dashboard</h1>",
    featured_image: "https://example.com/dashboard-image.jpg",
    meta_title: "Dashboard",
    meta_description: "This is the admin dashboard.",
    meta_keywords: "dashboard, admin",
    seo_heading: "Admin Dashboard",
    canonical_url: "https://mycompany.com/admin",
    is_published: 1,
    page_order: 1,
    created_by: 1,
  },
  {
    title: "Menus",
    slug: "menus-items",
    content: "<h1>Configure your menus</h1>",
    featured_image: "https://example.com/menus-image.jpg",
    meta_title: "Menus",
    meta_description: "Manage your menus easily.",
    meta_keywords: "menus, admin",
    seo_heading: "Menus Management",
    canonical_url: "https://mycompany.com/admin/menus",
    is_published: 1,
    page_order: 2,
    created_by: 1,
  },
  {
    title: "Pages",
    slug: "pages",
    content: "<h1>Manage your pages</h1>",
    featured_image: "https://example.com/pages-image.jpg",
    meta_title: "Pages",
    meta_description: "Edit and organize pages.",
    meta_keywords: "pages, admin",
    seo_heading: "Pages Management",
    canonical_url: "https://mycompany.com/admin/pages",
    is_published: 1,
    page_order: 3,
    created_by: 1,
  },
  {
    title: "Armada",
    slug: "armada",
    content: "<h1>Manage your fleet</h1>",
    featured_image: "https://example.com/armada-image.jpg",
    meta_title: "Armada",
    meta_description: "Manage your armada data.",
    meta_keywords: "armada, admin, fleet",
    seo_heading: "Armada Management",
    canonical_url: "https://mycompany.com/admin/armada",
    is_published: 1,
    page_order: 4,
    created_by: 1,
  },
  {
    title: "Partner",
    slug: "partner",
    content: "<h1>Manage partners</h1>",
    featured_image: "https://example.com/partner-image.jpg",
    meta_title: "Partner",
    meta_description: "Manage your business partners.",
    meta_keywords: "partner, admin, business",
    seo_heading: "Partner Management",
    canonical_url: "https://mycompany.com/admin/partner",
    is_published: 1,
    page_order: 5,
    created_by: 1,
  },
  {
    title: "Unit",
    slug: "unit",
    content: "<h1>Manage units</h1>",
    featured_image: "https://example.com/unit-image.jpg",
    meta_title: "Unit",
    meta_description: "Organize and edit units.",
    meta_keywords: "unit, admin",
    seo_heading: "Unit Management",
    canonical_url: "https://mycompany.com/admin/unit",
    is_published: 1,
    page_order: 6,
    created_by: 1,
  },
  {
    title: "Category",
    slug: "category",
    content: "<h1>Manage categories</h1>",
    featured_image: "https://example.com/category-image.jpg",
    meta_title: "Category",
    meta_description: "Organize and manage categories.",
    meta_keywords: "category, admin",
    seo_heading: "Category Management",
    canonical_url: "https://mycompany.com/admin/category",
    is_published: 1,
    page_order: 7,
    created_by: 1,
  },
  {
    title: "Usage Price",
    slug: "usage-price",
    content: "<h1>Manage categories</h1>",
    featured_image: "https://example.com/category-image.jpg",
    meta_title: "Usage Price",
    meta_description: "Organize and manage categories.",
    meta_keywords: "usage, price",
    seo_heading: "Usage Price",
    canonical_url: "https://mycompany.com/admin/category",
    is_published: 1,
    page_order: 8,
    created_by: 1,
  },
  {
    title: 'Renter OnBoarding',
    slug: 'renter-onboarding',
    content: '<h1>Renter OnBoarding</h1>',
    featured_image: 'https://example.com/renter-onboarding-image.jpg',
    meta_title: 'Renter OnBoarding',
    meta_description: 'Onboarding for renters.',
    meta_keywords: 'renter, onboarding',
    seo_heading: 'Renter OnBoarding',
    canonical_url: 'https://mycompany.com/renter',
    is_published: 1,
    page_order: 9,
    created_by: 1
  },
  {
    title: 'Order History',
    slug: 'order-history',
    content: '<h1>Order History</h1>',
    featured_image: 'https://example.com/order-history-image.jpg',
    meta_title: 'Order History',
    meta_description: 'View order history.',
    meta_keywords: 'order, history',
    seo_heading: 'Order History',
    canonical_url: 'https://mycompany.com/renter/order',
    is_published: 1,
    page_order: 10,
    created_by: 1
  }
];
